### ISSUE TITLE
Issue with initial set up, when running gulp

### ISSUE THREAD

**Issue by kmaneshk** [ngOfficeUIFabric/ng-officeuifabric#270]
I am having an issue with the initial set up. I was following the steps mentioned in the Minimal path to awesome article and when I run the **gulp** command in the [Transpile the Typescript](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/docs/guides/MPA.md#transpile-the-typescript) section, I am getting a different error to the one that is mentioned in the article.
### Expected Behavior

When I run the command, according to the article the error should be as below

module.js:339
    throw err;
    ^

Error: Cannot find module './build/gulp/config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ac/Dev/Scratch/ng-officeuifabric/gulpfile.js:3:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
### Actual Behavior

But instead the error that I am getting is this one

λ gulp 
[18:49:17] Failed to load external module ts-node/register
[18:49:17] Failed to load external module typescript-node/register
[18:49:17] Failed to load external module typescript-register
[18:49:17] Failed to load external module typescript-require
I:\Code\OpenSource\Angular\ng-officeuifabric\gulpfile.ts:3
import \* as fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Users\manesh.a.karunakaran\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\manesh.a.karunakaran\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:193:16)
    at module.exports (C:\Users\manesh.a.karunakaran\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
### Steps to Reproduce Behavior

Run gulp

I installed the missing modules globally from npm but the error just changes to 

_Requiring external module ts-node/register_

I am using a Win 8 machine, with 

node v0.12.2
typescript Version 1.8.9
npm 2.7.4

**Comment by kmaneshk** [comment]
I was able to fix the issue by adding the missing modules as dev dependencies and then deleting the contents of the typings folder and running a **typings install** again. WinMerge tells me that the newly generated files are using different carriage returns. I assume that would be because most of/all you are using MacOS

If you want me to commit the package.json with the dev dependencies, let me know, happy to send a pull request :)

**Comment by jjczopek** [comment]
Have you installed `gulp` globally?
Also, have you considered upgrading `node` & `npm`? I think we have started the project when version 4 of NPM was already old ;) I'm running now node 5.4.1 and npm 3.3.12 ;)

**Comment by kmaneshk** [comment]
Thanks @jjczopek. Upgraded to node 5.10.0 and the issue went away. Seems like my attempt to take you guys back to stone age didn't work ;)
